### ISSUE TITLE
About direct usage

### ISSUE THREAD

**Issue by Fubuki901** [cure-lab/SmoothNet#1]
Seems very useful!
So if I want to refine a 3D keypoints sequences, which checkpoint is good generally?
And since it is trained on 3D positions, why it can be used on a rotation sequences (like SMPL) as well?

**Comment by ailingzengzzz** [comment]
Hi @Fubuki901,

SmoothNet is a temporal-only model without spatial modeling, making it share weights among the spatial dimension. It only learns motion smoothness priori. Thus, it can cross modalities (2d, 3d, 6d, etc.) and generalize well.
