### ISSUE TITLE
Wrong skeleton in Visualization of PW3D_SPIN_3D_JOINTS.

### ISSUE THREAD

**Issue by Asakurayoho** [cure-lab/SmoothNet#12]
I found that the skeleton of PW3D_SPIN_3D was misplaced when I tried to visualize the pw3d_spin_3d pretrained model. I wonder if there may be some errors in the PW3D_SPIN_3D_JOINTS or PW3D_SPIN_3D_EDGES settings?
As follow:
![IMG_export_20220809_164055438](https://user-images.githubusercontent.com/26902636/183721515-1b2cfb01-bd32-4186-8adc-7ecf2b6ed6fe.jpg)

**Comment by juxuan27** [comment]
Hi, @Asakurayoho ! Thank you for your focus.
We apologize for the bug and have revised it. Please pull the latest code and the revised visualization will be like:
![image](https://user-images.githubusercontent.com/89566272/184081581-9b083f9d-730a-4686-86d6-350f106004f3.png)

**Comment by Asakurayoho** [comment]
@juxuan27 ，Thanks for your reply~
