### ISSUE TITLE
how to use smoothnet for actual usage？

### ISSUE THREAD

**Issue by squidward2021** [cure-lab/SmoothNet#13]
thank you for your work！I just wonder how to use it for actual usage

**Comment by ailingzengzzz** [comment]
Hi @squidward2021,

Thanks for your interest! Could you please explain what the actual usage is?

**Comment by squidward2021** [comment]
> Hi @squidward2021,
> 
> Thanks for your interest! Could you please explain what the actual usage is?

jitters elimination for 2d pose estimation

**Comment by squidward2021** [comment]
> Hi @squidward2021,
> 
> Thanks for your interest! Could you please explain what the actual usage is?

jitters elimination for 2d pose estimation

**Comment by ailingzengzzz** [comment]
Sure. Table 2 in the main paper shows the results of smoothing 2d poses.
