### ISSUE TITLE
Another question about MuPoTS-3d data

### ISSUE THREAD

**Issue by Asakurayoho** [cure-lab/SmoothNet#16]
Sorry but I have another question.
I tried to map the groundtruth and predicted points to the original video in MuPoTS-3d dataset. And I found the position in the file
`./data/poses/mupots_tposenetrefinenet_3D/groundtruth/mupots_gt_3D_test.npz` is a normalized format (Human 3.6M format?), which is described in the paper as: "We compare them on the universal coordinates, where each person is rescaled according to the hip and has a normalized height". 
Is there any way to recover absolute pose position or visualize it?

**Comment by ailingzengzzz** [comment]
Hi @Asakurayoho,

We did not save the absolute root position and the corresponding camera parameters. All results are from this repo: https://github.com/vegesm/pose_refinement.

**Comment by Asakurayoho** [comment]
Thanks~I'll read papers and codes about TposeNet.
