### ISSUE TITLE
Why SMPL rotation is 3 not 3*3?

### ISSUE THREAD

**Issue by jinfagang** [cure-lab/SmoothNet#18]
HI., I saw there has an option, smpl 6d, why it only have 24*3 and 24*6

rotation matrix why not be 24 * 3 *3? what's this 6d stands for?

**Comment by ailingzengzzz** [comment]
Hi @jinfagang,

All existing SMPL-Based methods directly regress 6D rotation matrix from the model (e.g., SPIN, PARE). You can find the function to transform 6d into 9d (3\*3) matrix ([rot6d_to_rotmat](https://github.com/cure-lab/SmoothNet/blob/main/lib/utils/geometry_utils.py#L63)).  
You can refer to this paper ([ On the continuity of rotation representations in neural networks](https://openaccess.thecvf.com/content_CVPR_2019/papers/Zhou_On_the_Continuity_of_Rotation_Representations_in_Neural_Networks_CVPR_2019_paper.pdf)) to understand why existing SMPL-Based models use it. Thanks!

**Comment by jinfagang** [comment]
My question is why your input shape is 24x3 and 24x6, in rotation matrix, shouldn't it be 24x3x3 and 24x3x4 (rot6d is R and T)?

**Comment by ailingzengzzz** [comment]
Sure, but 6D representation is enough. You can transform them into each other. Try it.

**Comment by ailingzengzzz** [comment]
Please try to reshape the input of SmoothNet as [N, C, T]. C is 24\*3\*3. T is a window size.

**Comment by jinfagang** [comment]
@ailingzengzzz Does NxT=Seqlen?

**Comment by ailingzengzzz** [comment]
Yes, if there is no overlap among the sliding windows.
