### ISSUE TITLE
Jitter performance not improved

### ISSUE THREAD

**Issue by mangguoxia** [cure-lab/SmoothNet#19]
Hi, I tested the jitter performance by using serveral pretrained models after normalize the data.
But, the jitter performance is similiar or a little bit worse. Do you have some suggestions ?

**Comment by ailingzengzzz** [comment]
Hi @mangguoxia,
Could you please provide more information about the datasets and pose estimators you used? Or could you provide a demo video?

From our in-the-wild test, there will be a great improvement in jitters for any sequences.

**Comment by mangguoxia** [comment]
Hi, I sent you an email, could you please check your gmail?

**Comment by squidward2021** [comment]
> Hi, I tested the jitter performance by using serveral pretrained models after normalize the data. But, the jitter performance is similiar or a little bit worse. Do you have some suggestions ?

Could you please explain how to  use pretrained model for jitter mitigation

**Comment by ailingzengzzz** [comment]
Hi @squidward2021,

I have replied @mangguoxia via email. Could you please describe your usage of SmoothNet? Do you use it for online or offline scenes?
