### ISSUE TITLE
Is there any generalization ability for the 21-point key points of the hand?

### ISSUE THREAD

**Issue by yangninghua** [cure-lab/SmoothNet#2]
It's a cool job, and it's eye-catching, but can this only be estimated by human body posture? Is there any generalization ability for the 21-point key points of the hand?

**Comment by ailingzengzzz** [comment]
Hi @yangninghua ,
Thanks for your interest! We have tested SmoothNet on the Whole Body demo (including face, body, and hand). The pre-trained models can also be used for hand directly, but we do not guarantee their effectiveness. The potential reason may be different motion distribution (e.g., acceleration pattern). 
For better performance, you can train SmoothNet on your hand dataset. Look forward to your feedback!
