### ISSUE TITLE
function of slide_window_to_sequence ???

### ISSUE THREAD

**Issue by xuhaozheng** [cure-lab/SmoothNet#21]
I wonder what's the functionality of slide_window_to_sequence(), it seems to average values single axis of the whole slide window. Why not use the single frame rather than the averaged frames for prediction?

**Comment by juxuan27** [comment]
Hi, @xuhaozheng ! Thank you for your focus!
You are right about slide_window_to_sequence(), it will average the SmoothNet output of a single frame from several slide windows. And then transfer batches to a whole sequence. This operation can lead to a slightly better result than using only output from a single slide window. And this is why we do this. You can adjust this operation by changing cfg.EVALUATE.SLIDE_WINDOW_STEP_SIZE. If this config value is settled to 1, the code will do the sliding window average operation. Else if it is settled to ``window size``, it will only do SmoothNet once for every single frame.

**Comment by juxuan27** [comment]
Specifically, the sliding window average operation can avoid spikes between the neighboring sliding windows. Here, spikes mean although frames in a single sliding window are smoothed, the last frame in the prior sliding window and the first frame in the next sliding window may suffer from jitters.
