### ISSUE TITLE
convert onnx

### ISSUE THREAD

**Issue by llpspark** [cure-lab/SmoothNet#22]
great work for 3D task!
I wonder to know how can I convert  the model  to onnx.

**Comment by juxuan27** [comment]
Hi, @llpspark ! Thank you for your focus!
May you specify your question? If you simply hope to convert the model to onnx, I believe code like ``torch.onnx.export`` can easily do it.

**Comment by llpspark** [comment]
> Hi, @llpspark ! Thank you for your focus!
> May you specify your question? If you simply hope to convert the model to onnx, I believe code like `torch.onnx.export` can easily do it.

I find it. thank you for your reply.
