### ISSUE TITLE
usage

### ISSUE THREAD

**Issue by RuiZhang-USTC** [cure-lab/SmoothNet#23]
Can I directly use the smoothnet to smooth the output of alphapose without any additional training? Thx

**Comment by ailingzengzzz** [comment]
Hi @RuiZhang-USTC ,
In theory, you can do it. We'd like to hear your feedback!

**Comment by RuiZhang-USTC** [comment]
> Hi @RuiZhang-USTC , In theory, you can do it. We'd like to hear your feedback!

The test had been done and the smoothnet is also suit for the alphapose.
