### ISSUE TITLE
restore

### ISSUE THREAD

**Issue by RuiZhang-USTC** [cure-lab/SmoothNet#24]
How to restore the estimation of the smoothnet with the same format of detected, namely, restore the imgname and keypoints while not the visual videos.

**Comment by wz1114841863** [comment]
I also want to Know，how to restore network output to 3D PW dataset format.

**Comment by juxuan27** [comment]
Hi, @RuiZhang-USTC and @wz1114841863 ! Thank you for your focus.
You need to add some code for restoration. For example, if you want to restore the SmoothNet result of 3D pose representation, you can add np.savez() [here](https://github.com/cure-lab/SmoothNet/blob/25772c28cb78b7f11bc979a469bbdfecac20cad9/lib/utils/eval_metrics.py#L567). And notice you need to store the results as you want [here](https://github.com/cure-lab/SmoothNet/blob/25772c28cb78b7f11bc979a469bbdfecac20cad9/lib/utils/eval_metrics.py#L518) in the loop of estimating each sequence, where the smoothed poses are stored in `denoised_pos`.
