### ISSUE TITLE
Can SmoothNet postprocess Mediapipe's OutPut?

### ISSUE THREAD

**Issue by Bruce-yu199** [cure-lab/SmoothNet#25]
Hi, SmoothNet is fantastic! And as the question metioned in the title, can i use SmoothNet for processing the 2D pose keypoints achieved by Google's Mediapipe?

**Comment by ailingzengzzz** [comment]
Hi @Bruce-yu199 ,

In theory, you can do it since SmoothNet shares weights across the spatial dimension. We'd like to hear your feedback!

**Comment by ywyw1** [comment]
Hello, I would like to ask how to do it specifically?

**Comment by Terrywang2001** [comment]
@ywyw1 Did you successfully postprocess any kind of output using SmoothNet?
