### ISSUE TITLE
Question (Plug and play)

### ISSUE THREAD

**Issue by mukeshnarendran7** [cure-lab/SmoothNet#26]
Hi, thanks for sharing your work. I have a standard HRNET W-48 model trained on my dataset for pose estimation. Can i use the smoothnet to that model to refine 2D keypoints or heatmap outputs?
Is this a temporal tracking model of keypoints?

**Comment by ailingzengzzz** [comment]
Hi @mukeshnarendran7,

Thanks for your interest! You can try our pre-trained model for your data. 
This is a smoothing strategy, where the input is a noisy sequence and the output is a smooth sequence, instead of temporal tracking models.
