### ISSUE TITLE
如何处理Root点的位移

### ISSUE THREAD

**Issue by xy370283** [cure-lab/SmoothNet#29]
感谢作者，SmoothNet对于Pose的优化效果确实很好。
    
    我想知道的是，SmoothNet是否可以用于对Root点的位移进行平滑？按照示例，似乎没有对position的处理。
    
    期待回复，谢谢！

**Comment by ailingzengzzz** [comment]
Hi @xy370283,

Thanks for your interest! 
You may try to normalize the positions of the root joint into [-1, 1], and use SmoothNet for smoothing. Then, denormalize the positions into the original scale.

**Comment by GZY219** [comment]
> Hi [@xy370283](https://github.com/xy370283),
> 
> Thanks for your interest! You may try to normalize the positions of the root joint into [-1, 1], and use SmoothNet for smoothing. Then, denormalize the positions into the original scale.

I wonder why data should be normalized when inferencing, while normalization was not applied to the training data?
