### ISSUE TITLE
how to train custom yoga pose model?

### ISSUE THREAD

**Issue by akashAD98** [cure-lab/SmoothNet#30]
1)i have no idea how should i genrate data, i saw in redme ,you mentioned two things one is file & second ground truth , also file format is .npz , How should I generate this? what steps should I need to follow?
2) using this repo can I able to do custom yoga pose detection?

**Comment by juxuan27** [comment]
Hi, @akashAD98 ! Thank you for your focus.
1) As mentioned in the README, you need to generate ground truth pose and detected poses sequence. You can refer to [here](https://github.com/cure-lab/DeciWatch/blob/main/doc/data.md) for the specific data format.
2) May I know what’s the original data format so that I can give you detailed instructions?

**Comment by akashAD98** [comment]
@juxuan27 i have only images of diffrent yoga poses with respect to there folder, now I want to train & detect yoga poses.

i understood but not clear about how should I get .npz format

**Comment by juxuan27** [comment]
Incase you only have images, it might be hard for you to train the SmoothNet model using your custom data. The training procedure needs groudtruth poses for model learning. Of course you can annotate the poses of your yoga images, but this will be quite time consuming. So here is my advice:
- If you only want to see the performance of SmoothNet on your yoga poses, you may refer to [here](https://github.com/open-mmlab/mmhuman3d/blob/main/mmhuman3d/core/post_processing/smooth/smoothnet.py) and [here](https://github.com/open-mmlab/mmhuman3d/blob/main/configs/_base_/post_processing/README.md).  MMHuman3D provides demo for arbitrary image/video input inference.
- If you still want to train on your own dataset, you can try to generate Pseudo-Labels using a SOTA model (e.g. ViTPose for 2D pose estimation). And then use them as ground truth. For the question of  how to get .npz format, you can simply use
```
import numpy as np
np.savez("xxx.npz", imgname=xxx, shape=xxx, pose=xxx, joints_3d=xxx, )
```
Hope this can help you.
