### ISSUE TITLE
H36M_HRNET_2D_EDGES show wrong results?

### ISSUE THREAD

**Issue by codylcs** [cure-lab/SmoothNet#31]
H36M_HRNET_2D_EDGES https://github.com/cure-lab/SmoothNet/blob/3eb7a85534da868e54ff866622ff4c7976733fa9/lib/visualize/visualize_skeleton.py#L796

should be [5, 6, 0],please check again

**Comment by juxuan27** [comment]
Hi @codylcs ! Thank you for pointing out the typo error. We have already revised it to [5,6,0].
