### ISSUE TITLE
run with different keypoints number

### ISSUE THREAD

**Issue by RustyShackleford73** [cure-lab/SmoothNet#35]
I had train a customize pose detector for 12 joints.
Is smoothnet works without retrain the weight or just to input the joints with coordinates like 0,0,0?

**Comment by oxysoft** [comment]
I just had a similar question as well, I only have two 3D points for each hand recorded from VR controllers, so I'm wondering if it'd be possible to get some SmoothNet on those since the movement remains human in nature, even if the rest of the body is missing.

**Comment by ailingzengzzz** [comment]
Hi @oxysoft @RustyShackleford73 ,

I'm sorry for the late reply.
Yes. SmoothNet supports any keypoint dimension since it is a temporal model and shares weights across spatial keypoint dimensions. You can have a try!
