### ISSUE TITLE
如何在mmpose中使用smoothnet平滑2d姿态

### ISSUE THREAD

**Issue by AgileChen3** [cure-lab/SmoothNet#36]
您好，
       如果我想在mmpose中使用smoothnet平滑2D姿态估计器得出的关键点，我应该怎么做呢？mmpose官方的api接口好像就适用于基于滤波器的方法。

**Comment by ailingzengzzz** [comment]
Hi @AgileChen3,

Recently, MMPose has improved the overall implementations into version1+; thus SmoothNet has been removed temporarily. You may refer to the previous version.
We implemented SmoothNet in the MMPosev0.25.0 ([link](https://github.com/open-mmlab/mmpose/releases/tag/v0.25.0)). We provide some [checkpoints](https://github.com/open-mmlab/mmpose/blob/v0.25.0/configs/_base_/filters/smoothnet_h36m.md) to smooth the results.

**Comment by ywyw1** [comment]
我如果要用其他如yolo-pose该怎么办
