### ISSUE TITLE
Motion-aware SmoothNet

### ISSUE THREAD

**Issue by HospitableHost** [cure-lab/SmoothNet#37]
Hi! Nice work, I read the lib/models/smoothnet.py, but I didn't find the code of Motion-aware SmoothNet. So have you already released that code?

**Comment by ailingzengzzz** [comment]
Hi @HospitableHost,

We did not release it. It may be implemented based on the basic version. 
In this repo, we report the results of the basic version. I hI hope it will be helpful to you.
