### ISSUE TITLE
VIBE Result is different from vibe paper

### ISSUE THREAD

**Issue by rabbitchenrui** [cure-lab/SmoothNet#39]
Hey, nice work, I have a question that why vibe result presented in your github is different from that of vibe's paper?
![QQ图片20230411214135](https://user-images.githubusercontent.com/114126263/231182338-deeeafc3-601c-436d-8a0b-2157334ee018.png)
![image](https://user-images.githubusercontent.com/114126263/231182543-10fe6ed9-ebbb-463c-8b29-da821bc92dee.png)

**Comment by ailingzengzzz** [comment]
Hi @rabbitchenrui,

We used the provided checkpoint from the original VIBE repo to test our prepared datasets. 
Notably, we drop the latest frames to satisfy the window size. If you follow our work to compare with your method, you can use our provided VIBE outputs for a fair comparison.
