### ISSUE TITLE
Motion-aware smoothnet

### ISSUE THREAD

**Issue by kxhaaa** [cure-lab/SmoothNet#41]
Hi,

I'm trying to implement Motion-aware SmoothNet. And it's a little bit confusing about the $T^e$ . Should they output the same same number of $T^e$ or just like the number of input $T, T-1, T-2$? 

Besides, for inference pipeline, which frames should be updated in the window? For example, in a 8 frames sequneces, should all frames be updated or just the middle frames? 

Thanks.

**Comment by ailingzengzzz** [comment]
Hi @kxhaaa,

1. The output $T_{th}$ frame should be the same index as the input frame.
2. For an 8-frame sequence, we would update all frames.
