### ISSUE TITLE
checkpoints is not a pretrained model!!!!

### ISSUE THREAD

**Issue by Ared521** [cure-lab/SmoothNet#42]
Hello, I downloaded your pretrained model. When I tested and trained, there was a problem. data/checkpoints/pw3d_spin_3D/checkpoints_8.pth.tar is not a pretrained model!!!!   Can you tell me how to solve it?

**Comment by wattanapong** [comment]
I found that it should be "data/checkpoints/pw3d_spin_3D/checkpoint_8.pth.tar " remove **"s"** at the end of **"checkpoint"**
