### ISSUE TITLE
3D pose estimator results are different from paper

### ISSUE THREAD

**Issue by wattanapong** [cure-lab/SmoothNet#43]
I tested human3.6M dataset on FCN estimator by using your testing guideline.

`python train_smoothnet.py --cfg configs/h36m_fcn_3D.yaml --dataset_name h36m --estimator fcn --body_representation 3D --slide_window_size 8`

Predicted estimator results are the same as paper, including Accel, MPJPE, and PA-MPJPE. However SmoothNet results are different.

In the paper, Accel, MPJPE, and PA-MPJPE are 1.03, 52.72, and 40.92, respectively. In contrast, your checkpoint results are 1.94, 53.29, and 41.38.

Is there any setting that I need to change? Please suggest to me.

**Comment by ailingzengzzz** [comment]
Hi @wattanapong,

Thanks for the feedback. You can use our provided checkpoint to test the results [here](https://drive.google.com/drive/folders/14qQvMqlk6K9QdSbtkmIAb7PdTGkRLIS_?usp=share_link). 
Do you use the same Pytorch version and follow the requirements?

**Comment by wattanapong** [comment]
@ailingzengzzz Thank you for your reply. I found that it was my mistake. Your evaluation code works well and produce exact results as your paper.
