### ISSUE TITLE
RLE 2D,3D and other dateset

### ISSUE THREAD

**Issue by AgileChen3** [cure-lab/SmoothNet#44]
Hello, the dataset you provided does not include the training set of RLE2D, 3D and VPose3D, can you upload the relevant dataset, thank you very much.

**Comment by ailingzengzzz** [comment]
Hi @AgileChen3，

We did not use the training set of  RLE2D, 3D, and VPose3D, but directly tested on the corresponding test sets to validate our generalization ability.
