### ISSUE TITLE
该网络是否能够即插即用，兼容不同模型与数据集

### ISSUE THREAD

**Issue by YHaooo-4508** [cure-lab/SmoothNet#45]
作者您好，了解到smoothnet是即插即用的，我想要将smoothnet直接用于我们当前的3D姿态估计预测结果，使用的是NTU数据集，但加载的是h36m_fcn_3D的cfg与模型，效果非常差。我想问一下，smoothnet是与网络模型还有数据集绑定的么，如果我想用smoothnet做3D姿态估计后处理优化，是不是需要重新在自己的数据集和网络上进行训练。

**Comment by ailingzengzzz** [comment]
Hi @YHaooo-4508,

SmoothNet is a learning-based model for smoothing. It is plug-and-play for different motion representations (e.g., 3d positions, 2d positions, or angles), and it can cross different datasets and backbone predictions (please see our main paper and appendix for the details). However, to get better smoothing results need to use similar data/motion distribution trained on SmoothNet. You can try other provided checkpoints for the inference comparisons. 
If you can train on your own data, it usually can get better results.
