### ISSUE TITLE
你的模型输入是什么意思？1440, 8, 32代表什么意思，怎么用的自己的网络中

### ISSUE THREAD

**Issue by yzl1014** [cure-lab/SmoothNet#5]

**Comment by yzl1014** [comment]
我在测试h36m数据时，发现数据格式是（1440,8,32），1440是什么意思

**Comment by juxuan27** [comment]
@yzl1014 你好！感谢关注！
我们已处理妥当的数据格式通常格式如下：
- SMPL：包括 imgname、pose、shape字段
  3D Keypoints：包括 imgname、joints_3d 字段
  2D Keypoints：包括 imgname、joints_2d 字段
- 每个字段的内部数据格式为 【视频序列数量×对应视频序列帧数×每帧对应数据】，更为具体的信息您可以参考[DeciWatch说明文档](https://github.com/cure-lab/DeciWatch/blob/main/doc/data.md)，SmoothNet 与 DeciWatch 的数据字段处理非常相似。

在输入到模型时，我们会将数据处理成【滑窗数量×滑窗大小×每帧对应数据】从而方便模型输入输出，即您问题中的1440为该测试视频序列可以分割出的滑窗数量，8为滑窗大小，32为每帧对应数据（16个关键点×2维坐标）。

**Comment by yzl1014** [comment]
模型最终的预测结果是这8个滑窗的均值？那这8个滑窗包含当前帧吗？

**Comment by yzl1014** [comment]
我发现一个问题，针对快速移动的物体，[SmoothNet]模型有严重的滞后性

**Comment by ailingzengzzz** [comment]
Hi @yzl1014,

Thanks for your quick feedback! Which pretrained model do you use?

**Comment by yzl1014** [comment]
h36m_fcn_3D/checkpoint_8.pth

**Comment by ailingzengzzz** [comment]
The smooth effectiveness will be influenced by the trained dataset (slow or fast movements). 
h36m_fcn_3D is a model trained on the Human3.6M dataset, which only contains a few fast-moving motions. You may try the models trained on the AIST++ dance dataset.

**Comment by yzl1014** [comment]
那我把输入帧数8改小，改成4或3，能不能减小滞后性？会不会影响模型的稳定性

**Comment by juxuan27** [comment]
> 模型最终的预测结果是这8个滑窗的均值？那这8个滑窗包含当前帧吗？

In fact, 8 is the length of one slide window, instead of the sliding window number. When inputting a sliding window with the length of 8 (8 frames), SmoothNet will output a window with the length of 8. And in this circumstance, the current frames are just these 8 frames.

**Comment by juxuan27** [comment]
> 我发现一个问题，针对快速移动的物体，[SmoothNet]模型有严重的滞后性

Would you please show us some visualization examples of the delay? Most of the time (or in my visualization), especially when the window size is relatively small (like 8), I didn't see such a problem. Your findings are really interesting and may help us improve our work. Thank you!

**Comment by ailingzengzzz** [comment]
Hi @yzl1014,

Different from filters, shortening the window size will not help the seeming lags. I guess this is not the true timing lag but the over-smooth phenomenon.

**Comment by yzl1014** [comment]
> > 我发现一个问题，针对快速移动的物体，[SmoothNet]模型有严重的滞后性
> 
> Would you please show us some visualization examples of the delay? Most of the time (or in my visualization), especially when the window size is relatively small (like 8), I didn't see such a problem. Your findings are really interesting and may help us improve our work. Thank you!

**Comment by yzl1014** [comment]
![Uploading QQ截图20220727103649.png…]()

**Comment by yzl1014** [comment]
![QQ截图20220727103649](https://user-images.githubusercontent.com/62282939/181148631-08dc2d92-0a04-4c4b-9c9b-58ce7a70fb85.png)

**Comment by yzl1014** [comment]
没加SmoothNet时只是有抖动，加了之后，有了滞后性。

**Comment by yzl1014** [comment]
> The smooth effectiveness will be influenced by the trained dataset (slow or fast movements). h36m_fcn_3D is a model trained on the Human3.6M dataset, which only contains a few fast-moving motions. You may try the models trained on the AIST++ dance data

aist_vibe_3D/checkpoint_8.pth 模型同样存在滞后

**Comment by juxuan27** [comment]
Thank you for your reply. We didn't see such a phenomenon in our visualization. We guess maybe it is due to over-smooth on quick movement (especially quick repetitive motion), which makes the output looks like lags? What's more, I recommend you check the visualization code to examine whether detection results are aligned with the visualization images.

**Comment by yzl1014** [comment]
> whether detection results are aligned with the visualization imag

看你们的推理源码，我的理解是这样的，前面7帧结果和当前帧的结果共8帧图像的检测结果输入SmoothNet中，SmoothNet得到8帧图像的检测结果，这8帧图像的检测结果求均值得到当前帧最终预测的结果。下一帧的流程也是这样。我有没有用错SmoothNet

**Comment by ailingzengzzz** [comment]
It seems you use it differently from the original setting. You should not average the values in a window.

The basic usage is simply to cut a long video into N **non-overlap** windows (e.g., window size is T). Put N windows into SmoothNet (shape: [N, T, C]), and SmoothNet will output smooth poses with the same shape. You can output the poses as the final poses.

In our setting, we further use a sliding-window algorithm to relieve spikes among different windows and get better results. We move the window forward with a one-time step, thus the overlap window size is T-1. The model operation is the same as the above: Put N windows into SmoothNet (shape: [N, T, C]), and SmoothNet outputs smooth poses with the same shape. Then, we average poses **from the same position** (e.g., two values present the same video position but from different windows).

**Comment by yzl1014** [comment]
> It seems you use it differently from the original setting. You should not average the values in a window.
> 
> The basic usage is simply to cut a long video into N **non-overlap** windows (e.g., window size is T). Put N windows into SmoothNet (shape: [N, T, C]), and SmoothNet will output smooth poses with the same shape. You can output the poses as the final poses.
> 
> In our setting, we further use a sliding-window algorithm to relieve spikes among different windows and get better results. We move the window forward with a one-time step, thus the overlap window size is T-1. The model operation is the same as the above: Put N windows into SmoothNet (shape: [N, T, C]), and SmoothNet outputs smooth poses with the same shape. Then, we average poses **from the same position** (e.g., two values present the same video position but from different windows).

改过测试代码之后，还有一点滞后性，但没以前严重啦

**Comment by jiejiangd** [comment]
Is the model to obtain the modified pose only from the pose of the current frame without using the pose of the previous frame, although it is possible that the trained model has similar information. If I want to perform real-time video pose estimation, does the model only depend on model parameters and input pose values? So it's not the same form as the Kalman filter, right?

**Comment by jiejiangd** [comment]
> It seems you use it differently from the original setting. You should not average the values in a window.
> 
> The basic usage is simply to cut a long video into N **non-overlap** windows (e.g., window size is T). Put N windows into SmoothNet (shape: [N, T, C]), and SmoothNet will output smooth poses with the same shape. You can output the poses as the final poses.
> 
> In our setting, we further use a sliding-window algorithm to relieve spikes among different windows and get better results. We move the window forward with a one-time step, thus the overlap window size is T-1. The model operation is the same as the above: Put N windows into SmoothNet (shape: [N, T, C]), and SmoothNet outputs smooth poses with the same shape. Then, we average poses **from the same position** (e.g., two values present the same video position but from different windows).

I want to ask you a test question. Is the model to obtain the modified pose only from the pose of the current frame without using the pose of the previous frame, although it is possible that the trained model has similar information. If I want to perform real-time video pose estimation, does the model only depend on model parameters and input pose values? So it's not the same form as the Kalman filter, right?
