### ISSUE TITLE
SmoothNet SMPL model input

### ISSUE THREAD

**Issue by SonNguyen2510** [cure-lab/SmoothNet#50]
Dear author,

Thank you for your amazing work. There is something confuse me about your method.
In this image, you said that your model is trained on 3D position representations only, so if I use a SmoothNet for PARE model (SMPL result), should I input a 3D keypoints postions or 6D rotation matrix for the model?
thank you so much!
![Screenshot from 2023-08-25 15-36-21](https://github.com/cure-lab/SmoothNet/assets/53286816/72d62fdf-df56-4fcc-9ab1-1e6edc29d83c)

**Comment by ailingzengzzz** [comment]
Hi @SonNguyen2510,

We trained SmoothNet on 3D position motions, and you can use it to test on 6D rotation, 2D or 3D positions due to the share-weight scheme across spatial dimensions.
