### ISSUE TITLE
SMPL parameters as input

### ISSUE THREAD

**Issue by yufu-liu** [cure-lab/SmoothNet#51]
Hi, thanks for this promising work!

I am wondering that can I use this model without an estimator?
For my purpose, it is just to mitigate the jitter of data, which reconstructed from labeled Mocap instead of images.

ex. SMPL parameters -> SmoothNet -> refined SMPL parameters

**Comment by ailingzengzzz** [comment]
Hi @yufu-liu,

You can try to use it or temporal filters for any normalized Mocap data.
