### ISSUE TITLE
On the issue of temporal processing of 3DPW datasets

### ISSUE THREAD

**Issue by Xushuolin** [cure-lab/SmoothNet#52]
May I ask, among the 3DPW datasets there are often sudden shifts in camera perspective, shaking, flipping. and occlusion of other characters. Does this affect the measurement of acceleration on the time series? Or is there a need to pre-process the dataset.

**Comment by ailingzengzzz** [comment]
Hi @Xushuolin,

Thanks for the kind feedback. We simply regard the sequences in 3DPW as smooth sequences. You can check the sequences containing sudden shifts whether we need to conduct specific processes on these videos.
