### ISSUE TITLE
The results of the 3dpw data set are different from  your paper

### ISSUE THREAD

**Issue by jihg88** [cure-lab/SmoothNet#53]
Thanks for your great work for removing jitter，but  some of the results in the paper confuse me.
The results of the first three lines of the 3dpw 3D format in the paper are as follows:
![image](https://github.com/cure-lab/SmoothNet/assets/50345299/6a4bef15-2650-47a4-a4d5-ba13328d37a8)
But when I tested, the input results were indeed the same as here on the homepage. I don’t know if the data set used for testing is different.
![image](https://github.com/cure-lab/SmoothNet/assets/50345299/14ec09f2-b5e7-45d0-a36d-8bdc0fb130ec)
By the way, the 3dpw’s GT you provided also seems to have jitters and mutations. Is this normal?

**Comment by ailingzengzzz** [comment]
Hi @jihg88 ,

1. The differences come from the different versions of code implementation. We encourage you to use the results from this repo, and you can develop better algorithms with fair comparisons.
2. For 3dpw GT, we did not process the original data. The jitter and mutations may be from the original IMU and monocular capture, which will not be perfect.

**Comment by jihg88** [comment]
Thank you so much！
