### ISSUE TITLE
filter_pose ?

### ISSUE THREAD

**Issue by luoww1992** [cure-lab/SmoothNet#6]
when i run it with smpl，
![image](https://user-images.githubusercontent.com/45957595/181150965-172d0dd9-ade2-4c4f-a771-2c228debcb07.png)

cmd: python eval_smoothnet.py --cfg configs/h36m_fcn_3D.yaml --checkpoint data/checkpoints/h36m_fcn_3D/checkpoint_32.pth.tar --dataset_name aist --estimator tcmr --body_representation smpl --slide_window_size 32

Q：[WARN] Cannot find rule for <class 'lib.models.smoothnet.SmoothNet'>. Treat it as zero Macs and zero Params.
it is no effect for smoothing?
what happend ?

**Comment by juxuan27** [comment]
Hi, @luoww1992 ! Thank you for your focus!
You may just ignore this warning. This would not influence the smoothing results.
