### ISSUE TITLE
EVALUATE.ROOT_RELATIVE

### ISSUE THREAD

**Issue by jiejiangd** [cure-lab/SmoothNet#7]
I would like to ask what the parameter EVALUATE.ROOT_RELATIVE is used for. The default setting is True. And the predicted value of the network  and gt becomes 0 after calculation with this parameter

**Comment by ailingzengzzz** [comment]
This is a parameter used in relative-root (e.g., root keypoint is the index 0 keypoint) 3D human pose estimation since we only calculate the errors under zero-root 3d pose instead of absolute 3d positions under the camera coordination.
If you have no such constraint in your task, you can set it as False.

**Comment by jiejiangd** [comment]
> This is a parameter used in relative-root (e.g., root keypoint is the index 0 keypoint) 3D human pose estimation since we only calculate the errors under zero-root 3d pose instead of absolute 3d positions under the camera coordination. If you have no such constraint in your task, you can set it as False.
I would like to ask again, what is the problem that PA-MPJPE index has always been nan while other indicators are normal

**Comment by jiejiangd** [comment]
It occurred to me that if I only had one feature point it would be inappropriate to use this index because there was no way to standardize it

**Comment by jiejiangd** [comment]
> This is a parameter used in relative-root (e.g., root keypoint is the index 0 keypoint) 3D human pose estimation since we only calculate the errors under zero-root 3d pose instead of absolute 3d positions under the camera coordination. If you have no such constraint in your task, you can set it as False.

It occurred to me that if I only had one feature point it would be inappropriate to use this index because there was no way to standardize it

**Comment by jiejiangd** [comment]
> This is a parameter used in relative-root (e.g., root keypoint is the index 0 keypoint) 3D human pose estimation since we only calculate the errors under zero-root 3d pose instead of absolute 3d positions under the camera coordination. If you have no such constraint in your task, you can set it as False.

It occurred to me that if I only had one feature point it would be inappropriate to use the PA-MPJPE  index because there was no way to standardize it

**Comment by jiejiangd** [comment]
> This is a parameter used in relative-root (e.g., root keypoint is the index 0 keypoint) 3D human pose estimation since we only calculate the errors under zero-root 3d pose instead of absolute 3d positions under the camera coordination. If you have no such constraint in your task, you can set it as False.

It occurred to me that if I only had one feature point it would be inappropriate to use the PA-MPJPE  index because there was no way to standardize it

**Comment by ailingzengzzz** [comment]
If you do not need to evaluate PA-MPJPE, you can ignore or uncomment it. 
This is a specific metric in the 3D pose. For details, you can check how PA-MPJPE calculates and find where to get the NAN.
