### ISSUE TITLE
Whether the order and quantity of key points during training and reasoning should be consistent？

### ISSUE THREAD

**Issue by HiiHongFe** [cure-lab/SmoothNet#9]
Hi！Guys！
I like your work very much! However, I have some questions to ask you, that is whether the order and number of key points in the data set during training should be consistent with that during reasoning. If I have 18 key points during training, but only 17 key points during reasoning and the order is different, can this be generalized to my task ?

**Comment by ailingzengzzz** [comment]
Hi @HiiHongFe,
There is no need for the order and the fixed number along the spatial axis/dimension since SmoothNet shares weight across the spatial dimension.

**Comment by HiiHongFe** [comment]
> Hi @HiiHongFe, There is no need for the order and the fixed number along the spatial axis/dimension since SmoothNet shares weight across the spatial dimension.

Thank you for your answer! I will try to use it in my project. I hope to keep communicating with you and learn from you! salute!

**Comment by HiiHongFe** [comment]
> Hi @HiiHongFe, There is no need for the order and the fixed number along the spatial axis/dimension since SmoothNet shares weight across the spatial dimension.

@ailingzengzzz 
Thank you for your answer! I will try to use it in my project. I hope to keep communicating with you and learn from you! salute!
